playbooks: replace deprecated with_items with loop
Upgrading to Python 3.8.x greets users with broken with_items
functionality: Users were greeted with errors such as:

    sre_constants.error: bad character range l-d at position 34

These mysterious errors were not present in the 3.7.x series and below.

Replacing the use of "with_items:" with "loop:" fixed the issue and the
playbook proceeds as expected.

Fixes SE-2019